ZI/Controllers/TipZnanstvenogRadasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BLL;

namespace ZI.Controllers
{
    public class TipZnanstvenogRadasController : Controller
    {
        private BLL.BLLProviders.TipZnanstvenogRadaBLL tip_p = new BLL.BLLProviders.TipZnanstvenogRadaBLL();
        // GET: TipZnanstvenogRadas
        public ActionResult Index()
        {
            return View(tip_p.FetchAll());
        }

        // GET: TipZnanstvenogRadas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipZnanstvenogRada tipZnanstvenogRada = tip_p.Fetch(id.Value);
            if (tipZnanstvenogRada == null)
            {
                return HttpNotFound();
            }
            return View(tipZnanstvenogRada);
        }

        // GET: TipZnanstvenogRadas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipZnanstvenogRadas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Naziv")] TipZnanstvenogRada tipZnanstvenogRada)
        {
            if (ModelState.IsValid)
            {
                tip_p.Update(tipZnanstvenogRada);
                return RedirectToAction("Index");
            }

            return View(tipZnanstvenogRada);
        }

        // GET: TipZnanstvenogRadas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipZnanstvenogRada tipZnanstvenogRada = tip_p.Fetch(id.Value);
            if (tipZnanstvenogRada == null)
            {
                return HttpNotFound();
            }
            return View(tipZnanstvenogRada);
        }

        // POST: TipZnanstvenogRadas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Naziv")] TipZnanstvenogRada tipZnanstvenogRada)
        {
            if (ModelState.IsValid)
            {
                tip_p.Update(tipZnanstvenogRada);
                return RedirectToAction("Index");
            }
            return View(tipZnanstvenogRada);
        }

        // GET: TipZnanstvenogRadas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipZnanstvenogRada tipZnanstvenogRada = tip_p.Fetch(id.Value);
            if (tipZnanstvenogRada == null)
            {
                return HttpNotFound();
            }
            return View(tipZnanstvenogRada);
        }

        // POST: TipZnanstvenogRadas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TipZnanstvenogRada tipZnanstvenogRada = tip_p.Fetch(id);
            tip_p.Delete(tipZnanstvenogRada);
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

ZI/Controllers/ZaposlenjesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BLL;

namespace DZ22.Controllers
{
    public class ZaposlenjesController : Controller
    {
        private BLL.BLLProviders.ZaposlenjeBLL zap_p = new BLL.BLLProviders.ZaposlenjeBLL();

        // GET: Zaposlenjes
        public ActionResult Index()
        {
            return View(zap_p.FetchAll());
        }

        // GET: Zaposlenjes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zaposlenje zaposlenje = zap_p.Fetch(id.Value);
            if (zaposlenje == null)
            {
                return HttpNotFound();
            }
            return View(zaposlenje);
        }

        // GET: Zaposlenjes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Zaposlenjes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Naziv")] Zaposlenje zaposlenje)
        {
            if (ModelState.IsValid)
            {
                zap_p.Insert(zaposlenje);
                return RedirectToAction("Index");
            }

            return View(zaposlenje);
        }

        // GET: Zaposlenjes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zaposlenje zaposlenje = zap_p.Fetch(id.Value);
            if (zaposlenje == null)
            {
                return HttpNotFound();
            }
            return View(zaposlenje);
        }

        // POST: Zaposlenjes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Naziv")] Zaposlenje zaposlenje)
        {
            if (ModelState.IsValid)
            {
                zap_p.Update(zaposlenje);
                return RedirectToAction("Index");
            }
            return View(zaposlenje);
        }

        // GET: Zaposlenjes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zaposlenje zaposlenje = zap_p.Fetch(id.Value);
            if (zaposlenje == null)
            {
                return HttpNotFound();
            }
            return View(zaposlenje);
        }

        // POST: Zaposlenjes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Zaposlenje zaposlenje = zap_p.Fetch(id);
            zap_p.Delete(zaposlenje);
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

ZI/Controllers/ZnanstveniRadsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BLL;

namespace ZI.Controllers
{
    public class ZnanstveniRadsController : Controller
    {
        private BLL.BLLProviders.ZnanstveniRadBLL rad_p = new BLL.BLLProviders.ZnanstveniRadBLL();
        private BLL.BLLProviders.TipZnanstvenogRadaBLL tip_p = new BLL.BLLProviders.TipZnanstvenogRadaBLL();

        // GET: ZnanstveniRads
        public ActionResult Index()
        {
            return View(rad_p.FetchAll());
        }

        // GET: ZnanstveniRads/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ZnanstveniRad znanstveniRad = rad_p.Fetch(id.Value);
            if (znanstveniRad == null)
            {
                return HttpNotFound();
            }
            return View(znanstveniRad);
        }

        // GET: ZnanstveniRads/Create
        public ActionResult Create()
        {
            //ViewBag.NastavnoOsobljeId = new SelectList(db.Djelatnik, "Id", "Ime");
            ViewBag.TipZnanstvenogRadaId = new SelectList(tip_p.FetchAll(), "Id", "Naziv");
            return View();
        }

        // POST: ZnanstveniRads/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,NastavnoOsobljeId,TipZnanstvenogRadaId,Naziv,Godina,SifraUpisa")] ZnanstveniRad znanstveniRad)
        {
            if (ModelState.IsValid)
            {
                rad_p.Insert(znanstveniRad);
                return RedirectToAction("Details", "Djelatniks", new { id = znanstveniRad.NastavnoOsobljeId });
            }

            //ViewBag.NastavnoOsobljeId = new SelectList(db.Djelatnik, "Id", "Ime", znanstveniRad.NastavnoOsobljeId);
            ViewBag.TipZnanstvenogRadaId = new SelectList(tip_p.FetchAll(), "Id", "Naziv", znanstveniRad.TipZnanstvenogRadaId);
            return View(znanstveniRad);
        }

        // GET: ZnanstveniRads/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ZnanstveniRad znanstveniRad = rad_p.Fetch(id.Value);
            if (znanstveniRad == null)
            {
                return HttpNotFound();
            }
          //  ViewBag.NastavnoOsobljeId = new SelectList(db.Djelatnik, "Id", "Ime", znanstveniRad.NastavnoOsobljeId);
            ViewBag.TipZnanstvenogRadaId = new SelectList(tip_p.FetchAll(), "Id", "Naziv", znanstveniRad.TipZnanstvenogRadaId);
            return View(znanstveniRad);
        }

        // POST: ZnanstveniRads/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,NastavnoOsobljeId,TipZnanstvenogRadaId,Naziv,Godina,SifraUpisa")] ZnanstveniRad znanstveniRad)
        {
            if (ModelState.IsValid)
            {
                rad_p.Update(znanstveniRad);
                return RedirectToAction("Details", "Djelatniks", new { id = znanstveniRad.NastavnoOsobljeId });
            }
            // ViewBag.NastavnoOsobljeId = new SelectList(db.Djelatnik, "Id", "Ime", znanstveniRad.NastavnoOsobljeId);
            ViewBag.TipZnanstvenogRadaId = new SelectList(tip_p.FetchAll(), "Id", "Naziv", znanstveniRad.TipZnanstvenogRadaId);
            return View(znanstveniRad);
        }

        // GET: ZnanstveniRads/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ZnanstveniRad znanstveniRad = rad_p.Fetch(id.Value);
            if (znanstveniRad == null)
            {
                return HttpNotFound();
            }
            return View(znanstveniRad);
        }

        // POST: ZnanstveniRads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ZnanstveniRad znanstveniRad = rad_p.Fetch(id);
            rad_p.Delete(znanstveniRad);
            return RedirectToAction("Details", "Djelatniks", new { id = znanstveniRad.NastavnoOsobljeId });
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

ZI/Controllers/ZvanjeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BLL;

namespace DZ22.Controllers
{
    public class ZvanjeController : Controller
    {
        private BLL.BLLProviders.ZvanjeBLL zva_p = new BLL.BLLProviders.ZvanjeBLL();

        // GET: Zvanje
        public ActionResult Index()
        {
            return View(zva_p.FetchAll());
        }

        // GET: Zvanje/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zvanje zvanje = zva_p.Fetch(id.Value);
            if (zvanje == null)
            {
                return HttpNotFound();
            }
            return View(zvanje);
        }

        // GET: Zvanje/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Zvanje/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Naziv")] Zvanje zvanje)
        {
            if (ModelState.IsValid)
            {

                zva_p.Insert(zvanje);
                return RedirectToAction("Index");
            }

            return View(zvanje);
        }

        // GET: Zvanje/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zvanje zvanje = zva_p.Fetch(id.Value);
            if (zvanje == null)
            {
                return HttpNotFound();
            }
            return View(zvanje);
        }

        // POST: Zvanje/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Naziv")] Zvanje zvanje)
        {
            if (ModelState.IsValid)
            {
                zva_p.Update(zvanje);
                return RedirectToAction("Index");
            }
            return View(zvanje);
        }

        // GET: Zvanje/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zvanje zvanje = zva_p.Fetch(id.Value);
            if (zvanje == null)
            {
                return HttpNotFound();
            }
            return View(zvanje);
        }

        // POST: Zvanje/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Zvanje zvanje = zva_p.Fetch(id);
            zva_p.Delete(zvanje);
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

ZI/Views/Djelatniks/Delete.cshtml
@model BLL.Djelatnik

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Brisanje djelatnika</h2>

<h3>Jeste li sigurni da želite obrisati ovog djelatnika ?</h3>
<div>
    <h4>@Model.Ime @Model.Prezime</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OIB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OIB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GodRodjenja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GodRodjenja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UredSoba)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UredSoba)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.E_mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.E_mail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrgJed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrgJed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipDjelatnika)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipDjelatnika)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zaposlenje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zaposlenje)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zvanje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zvanje)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <div class="col-md-offset-1 col-md-10">

                <input type="submit" value="Izbriši" class="btn btn-danger" />
                <input type="submit" onclick="window.history.back()" value="Odustani" class="btn btn-primary" />
            </div>
        </div>
        <br />
    }
</div>

ZI/Views/Djelatniks/Details.cshtml
@model ZI.Models.DjelatnikRadViewModel

@{
    ViewBag.Title = "Djelatnik";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.djelatnik.Ime @Model.djelatnik.Prezime
    @Html.ActionLink("Uredi", "Edit", new { id = Model.djelatnik.Id }, htmlAttributes: new { @class = "pull-right btn btn-success" })
</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.djelatnik.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.djelatnik.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.djelatnik.Prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.djelatnik.Prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.djelatnik.OIB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.djelatnik.OIB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.djelatnik.GodRodjenja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.djelatnik.GodRodjenja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.djelatnik.UredSoba)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.djelatnik.UredSoba)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.djelatnik.E_mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.djelatnik.E_mail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.djelatnik.Telefon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.djelatnik.Telefon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.djelatnik.OrgJed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.djelatnik.OrgJed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.djelatnik.TipDjelatnika)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.djelatnik.TipDjelatnika)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.djelatnik.Zaposlenje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.djelatnik.Zaposlenje)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.djelatnik.Zvanje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.djelatnik.Zvanje)
        </dd>

    </dl>
</div>

<div>

    <h3>Znanstveni radovi djelatnika
        @Html.ActionLink("Novi rad", "Create", "ZnanstveniRads", new { NastavnoOsobljeId = Model.djelatnik.Id }, htmlAttributes: new { @class = "pull-right btn btn-primary" })
    </h3>


    @if (Model.radovi.Count() > 0)
    {
        
        <table class="table table-striped table-hover" id="RadoviTable">
            <thead>
                <tr>
                    <th>
                        Naziv rada
                    </th>
                    <th>
                        Tip rada
                     @*   @Html.ActionLink("(Šifrarnik)", "Index", "TipZnanstvenogRadas")*@
                    </th>
                    <th>
                        Godina
                    </th>
                    <th>
                        Šifra upisa
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.radovi)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Naziv)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TipZnanstvenogRada)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Godina)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SifraUpisa)
                        </td>
                        <td>
                            @Html.ActionLink("Uredi", "Edit", "ZnanstveniRads", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-sm btn-default" }) 
                            @Html.ActionLink("Izbriši", "Delete", "ZnanstveniRads", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-sm btn-danger" }) 
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    }
    else
    {
        @Html.Partial("~/Views/Shared/_NoEntries.cshtml")
    }
</div>

<p>
<p>
    @Html.ActionLink("Povratak na listu djelatnika", "Index")
</p>
</p>

@section scripts {
<script>
        $(document).ready(function () {
            $('#RadoviTable').DataTable({
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.10.12/i18n/Croatian.json'
                }
            });
        });
</script>
}

ZI/Views/Djelatniks/Index.cshtml
@model IEnumerable<BLL.Djelatnik>

@{
    ViewBag.Title = "Popis djelatnika";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title
    @Html.ActionLink("Novi zapis", "Create", new { OrgJedId = Request.QueryString["orgJedID"] }, htmlAttributes: new { @class = "pull-right btn btn-primary" })
    </h2>

<div class="well row">
    <div class="col-xs-4">
        Prikazano <strong>@Model.Count()</strong> djelatnik(a).<br />
    </div>
    <form id="filterForm" class="col-sm-8">
        <div class="col-sm-6">
            <label for="fakultetId">Fakultet</label>
            @Html.DropDownList("orgJedID", null, htmlAttributes: new { @class = "form-control" })
        </div>
    </form>
</div>

@if (Model.Count() > 0)
{
<table class="table table-hover table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prezime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OIB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GodRodjenja)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UredSoba)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.E_mail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrgJed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipDjelatnika)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Zaposlenje)
            @Html.ActionLink("(Šifrarnik)", "Index", "Zaposlenjes")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Zvanje)
            @Html.ActionLink("(Šifrarnik)", "Index", "Zvanje")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prezime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OIB)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GodRodjenja)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UredSoba)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.E_mail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrgJed)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipDjelatnika)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Zaposlenje)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Zvanje)
        </td>
        <td>
            @Html.ActionLink("Uređivanje", "Edit", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-sm btn-primary" }) 
            @Html.ActionLink("Pojedinosti", "Details", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-sm btn-success" }) 
            @Html.ActionLink("Brisanje", "Delete", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-sm btn-danger" })
        </td>
    </tr>
}

</table>
}
else
{
    @Html.Partial("~/Views/Shared/_NoEntries.cshtml")
}

@section scripts {
    <script>
        var ff = '#filterForm';
        $(ff).on('change', function () {
            this.submit();
        });
    </script>
    }