ZI/Models/StudijskiProgramViewModel.cs
using BLL;
using System.Collections.Generic;

namespace ZI.Models
{
    public class StudijskiProgramViewModel
    {
        public StudijskiProgram StudijskiProgram { get; set; }
        public List<Predmet> Predmeti { get; set; }
        public PagingInfo PagingInfo { get; set; }
    }
}

ZI/Controllers/FakultetsController.cs
using BLL;
using BLL.BLLProviders;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ZI.Models;

namespace DZ22.Controllers
{
    /// <summary>
    /// Upravljač za rad s master-detail stranicom Fakulteti.
    /// </summary>
    public class FakultetsController : Controller
    {
        
        private BLL.BLLProviders.FakultetBLL fakBLL = new BLL.BLLProviders.FakultetBLL();

        private BLL.BLLProviders.SveucilisteBLL sveBLL = new BLL.BLLProviders.SveucilisteBLL();
        private List<Fakultet> fakulteti = new List<Fakultet>();


        /// <summary>
        /// GET postupak za prikaz Index stranice za fakultete
        /// Dohvaća popis svih fakulteta, sortira ih po parametrima i predaje pogledu.
        /// </summary>
        /// <param name="sveucilisteId">Uvjet sortiranja fakulteta</param>
        /// <returns>Rezultat akcije upravljača prikazuje popis faulteta.</returns>
        public ActionResult Index(int? sveucilisteId)
        {
            if (!sveucilisteId.HasValue || sveucilisteId == -1) {
                fakulteti = fakBLL.FetchAll().ToList();
            } else {
                fakulteti = fakBLL.FetchBySveuciliste(sveucilisteId.Value).ToList();
                
            }
            var sveucilista = sveBLL.FetchAll();
            sveucilista.Insert(0, new BLL.Sveuciliste() { Id = -1, Naziv = "--- Odaberite sveučilište ---" });

            object svSel = sveucilisteId.HasValue ? sveBLL.FetchByID(sveucilisteId.Value) : null;
            ViewData["SveucilisteId"] = new SelectList(sveucilista, "Id", "Naziv", svSel);
            return View(fakulteti);
        }

        /// <summary>
        /// Dohvaća popis svih organizacijskih jedinica određenog fakulteta
        /// Namještava straničenje
        /// </summary>
        /// <param name="id">Šifra fakulteta čije podatke želimo prikazati</param>
        /// <returns>Rezultat akcije upravljača prikazuje pogled Details s odabranim fakultetom i pripadajućim organizacijskim jedinicama.</returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var fakultet = fakBLL.FetchByID(id.Value);
            if (fakultet == null)
            {
                return HttpNotFound();
            }

            var bllOrgJed = new OrganizacijskaJedinicaBLL();
            var OrgJeds = bllOrgJed.FetchAll().Where(x => x.FakultetId == fakultet.Id);

            FakultetViewModel model = new FakultetViewModel
            {
                Fakultet = fakultet,
                OrgJedList = OrgJeds.ToList(),
                PagingInfo = null
            };

            return View(model);
        }

        /// <summary>
        /// Upravitelj za dohvaćanje podataka potrebnih za stranicu za kreiranje fakulteta.
        /// </summary>
        /// <param name="sveucID">Šifra sveučilišta kojem pripada fakultet koji kreiramo</param>
        /// <returns>Pogled za kreiranje fakulteta</returns>
        public ActionResult Create(int? sveucID)
        {
            var sveucilisteBLL = new BLL.BLLProviders.SveucilisteBLL();
            ViewBag.SveucilisteId = new SelectList(sveucilisteBLL.FetchAll(), "Id", "Naziv", sveucID);
            return View();
        }

        /// <summary>
        /// Upravitelj za dohvaćanje podataka potrebnih za stranicu za kreiranje fakulteta.
        /// </summary>
        /// <param name="fakultet">Novi fakultet koji se dodaje</param>
        /// <returns>Pogled za kreiranje fakulteta</returns>
        [HttpPost][ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SveucilisteId,Naziv,Kratica,Adresa,OIB,URL,IBAN")] BLL.Fakultet fakultet)
        {
            if (ModelState.IsValid)
            {
                fakBLL.Insert(fakultet);
                return RedirectToAction("Index");
            }
            var sveucilisteBLL = new BLL.BLLProviders.SveucilisteBLL();
            object selectedSv = sveBLL.FetchByID(fakultet.SveucilisteId);
            ViewBag.SveucilisteId = new SelectList(sveucilisteBLL.FetchAll(), "Id", "Naziv", selectedSv);
            return View(fakultet);
        }


        /// <summary>
        /// Upravitelj za dohvaćanje i prikaz podataka o fakultetu koji se uređuje.
        /// </summary>
        /// <param name="id">Broj fakulteta koji se uređuje</param>
        /// <returns>Pogled za uređivanje fakulteta</returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var fakultet = fakBLL.FetchByID(id.Value);
            if (fakultet == null)
            {
                return HttpNotFound();
            }
            var sveucilisteBLL = new BLL.BLLProviders.SveucilisteBLL();
            ViewBag.SveucilisteId = new SelectList(sveucilisteBLL.FetchAll(), "Id", "Naziv", fakultet.SveucilisteId);
            return View(fakultet);
        }

        /// <summary>
        /// POST metoda za uređivanje fakulteta
        /// </summary>
        /// <param name="fakultet">Podaci o fakultetu koje je potrebno spremiti</param>
        /// <returns>Stranicu Index na fakultetu koji je bio uređen</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SveucilisteId,Naziv,Kratica,Adresa,OIB,URL,IBAN")] BLL.Fakultet fakultet)
        {
            if (ModelState.IsValid)
            {
                fakBLL.Update(fakultet);
                return RedirectToAction("Index");
            }
            var sveucilisteBLL = new BLL.BLLProviders.SveucilisteBLL();
            ViewBag.SveucilisteId = new SelectList(sveucilisteBLL.FetchAll(), "Id", "Naziv", fakultet.SveucilisteId);
            return View(fakultet);
        }


        /// <summary>
        /// Upravitelj za dohvaćanje podataka za prikaz pogleda za potvrđivanje brisanja.
        /// </summary>
        /// <param name="id">Broj računa koji se briše</param>
        /// <returns>Stranicu za potvrdu brisanja računa</returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var fakultet = fakBLL.FetchByID(id.Value);
            if (fakultet == null)
            {
                return HttpNotFound();
            }
            return View(fakultet);
        }

        /// <summary>
        /// POST metoda koja se poziva kad se potvrdi brisanje fakulteta.
        /// </summary>
        /// <param name="id">Broj fakulteta koji se briše</param>
        /// <returns>Osvježenu Index stranicu s preostalim fakultetima</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var fakultet = fakBLL.FetchByID(id);
            fakBLL.Delete(fakultet);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZI/Controllers/PredmetsController.cs
using BLL;
using System.Net;
using System.Web.Mvc;

namespace DZ22.Controllers
{
    public class PredmetsController : Controller
    {
        private BLL.BLLProviders.PredmetBLL bllP = new BLL.BLLProviders.PredmetBLL();
        private BLL.BLLProviders.TipPredmetaBLL bllTP = new BLL.BLLProviders.TipPredmetaBLL();
        private BLL.BLLProviders.StudijskiProgramBLL bllSP = new BLL.BLLProviders.StudijskiProgramBLL();
        private BLL.BLLProviders.NastavniPlanBLL bllNP = new BLL.BLLProviders.NastavniPlanBLL();

        // GET: Predmets
        public ActionResult Index()
        {
            var predmet = bllP.FetchAll();
            return View(predmet);
        }

        // GET: Predmets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var predmet = bllP.FetchById(id.Value);
            if (predmet == null)
            {
                return HttpNotFound();
            }
            var model = new ZI.Models.PredmetNastavniPlanoviViewModel()
            {
                Predmet = predmet,
                NastavniPlanovi = bllNP.Fetch(predmet.Id)
            };
            return View(model);
        }

        // GET: Predmets/Create
        public ActionResult Create(int? studijskiProgramId)
        {
            object selectedSP = studijskiProgramId.HasValue ? bllSP.FetchById(studijskiProgramId.Value) : null;
            ViewBag.StudijskiProgramId = new SelectList(bllSP.FetchAll(), "Id", "Naziv", selectedSP);
            ViewBag.TipPredmetaId = new SelectList(bllTP.FetchAll(), "Id", "Naziv");
            return View();
        }

        // POST: Predmets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int? studijskiProgramId,
            [Bind(Include = "Id,TipPredmetaId,StudijskiProgramId,Naziv,IshodiUcenja")] Predmet predmet)
        {
            if (ModelState.IsValid)
            {
                bllP.Insert(predmet);
                return RedirectToAction("Index");
            }
            
            ViewBag.StudijskiProgramId = new SelectList(bllSP.FetchAll(), "Id", "Naziv", predmet.StudijskiProgramId);
            ViewBag.TipPredmetaId = new SelectList(bllTP.FetchAll(), "Id", "Naziv");
            return View(predmet);
        }

        // GET: Predmets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Predmet predmet = bllP.FetchById(id.Value);
            if (predmet == null)
            {
                return HttpNotFound();
            }
            
            ViewBag.StudijskiProgramId = new SelectList(bllSP.FetchAll(), "Id", "Naziv", predmet.StudijskiProgramId);
            ViewBag.TipPredmetaId = new SelectList(bllTP.FetchAll(), "Id", "Naziv", predmet.TipPredmetaId);
            return View(predmet);
        }

        // POST: Predmets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TipPredmetaId,StudijskiProgramId,Naziv,IshodiUcenja")] Predmet predmet)
        {
            if (ModelState.IsValid)
            {
                bllP.Update(predmet);
                return RedirectToAction("Details", new { id = predmet.Id });
            }
            
            ViewBag.StudijskiProgramId = new SelectList(bllSP.FetchAll(), "Id", "Naziv", predmet.StudijskiProgramId);
            ViewBag.TipPredmetaId = new SelectList(bllTP.FetchAll(), "Id", "Naziv", predmet.TipPredmetaId);
            return View(predmet);
        }

        // GET: Predmets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Predmet predmet = bllP.FetchById(id.Value);
            if (predmet == null)
            {
                return HttpNotFound();
            }
            return View(predmet);
        }

        // POST: Predmets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            bllP.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZI/Controllers/TipStudijasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BLL;

namespace DZ22.Controllers
{
    public class TipStudijasController : Controller
    {
        private BLL.BLLProviders.TipStudijaBLL bllTS = new BLL.BLLProviders.TipStudijaBLL();

        // GET: TipStudijas
        public ActionResult Index()
        {
            return View(bllTS.FetchAll());
        }

        // GET: TipStudijas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tipStudija = bllTS.Fetch(id.Value);
            if (tipStudija == null)
            {
                return HttpNotFound();
            }
            return View(tipStudija);
        }

        // GET: TipStudijas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipStudijas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Naziv")] BLL.TipStudija tipStudija)
        {
            if (ModelState.IsValid)
            {
                bllTS.Insert(tipStudija);
                return RedirectToAction("Index");
            }

            return View(tipStudija);
        }

        // GET: TipStudijas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tipStudija = bllTS.Fetch(id.Value);
            if (tipStudija == null)
            {
                return HttpNotFound();
            }
            return View(tipStudija);
        }

        // POST: TipStudijas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Naziv")] BLL.TipStudija tipStudija)
        {
            if (ModelState.IsValid)
            {
                bllTS.Update(tipStudija);
                return RedirectToAction("Index");
            }
            return View(tipStudija);
        }

        // GET: TipStudijas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tipStudija = bllTS.Fetch(id.Value);
            if (tipStudija == null)
            {
                return HttpNotFound();
            }
            return View(tipStudija);
        }

        // POST: TipStudijas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            bllTS.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZI/Views/StudijskiPrograms/Create.cshtml
@model BLL.StudijskiProgram

@{
    ViewBag.Title = "Stvaranje";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Studijski program</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.TipStudijaId, "TipStudijaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipStudijaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipStudijaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FakultetId, "FakultetId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FakultetId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FakultetId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Trajanje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Trajanje, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Trajanje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Stvori" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Svi studijski programi", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ZI/Views/StudijskiPrograms/Delete.cshtml
@model BLL.StudijskiProgram

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StudijskiProgram</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trajanje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trajanje)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fakultet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fakultet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipStudija)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipStudija)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ZI/Views/StudijskiPrograms/Details.cshtml
@model ZI.Models.StudijskiProgramViewModel

@{
    ViewBag.Title = "Studijski program";
}

<div class="page-header">

    <h2>
        @ViewBag.Title
        @Html.ActionLink("Uredi", "Edit", new { id = Model.StudijskiProgram.Id }, htmlAttributes: new { @class = "pull-right btn btn-success" })
    </h2>

    <div class="well">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.StudijskiProgram.Naziv)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StudijskiProgram.Naziv)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.StudijskiProgram.Trajanje)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StudijskiProgram.Trajanje)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.StudijskiProgram.Fakultet)
            </dt>

            <dd>
                @Html.ActionLink(Model.StudijskiProgram.Fakultet, "Details", "Fakultets", new { id = Model.StudijskiProgram.FakultetId }, null)
            </dd>

            <dt>
                Tip studija
                (@Html.ActionLink("Šifrarnik", "Index", "TipStudijas"))
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StudijskiProgram.TipStudija)
            </dd>

        </dl>
    </div>
</div>
<p>
    @Html.ActionLink("Svi studijski programi", "Index") 
</p>

<h3>
    Predmeti studijskog programa
    @Html.ActionLink("Novi zapis", "Create", "Predmets", new { studijskiProgramId = Model.StudijskiProgram.Id }, htmlAttributes: new { @class = "pull-right btn btn-primary" })
</h3>

@if (Model.Predmeti.Count() > 0)
{
    <table class="table table-hover table-striped" id="PredmetiTable">
        <thead>
            <tr>
                <th>
                    Naziv
                </th>
                <th>
                    Tip predmeta
                    (@Html.ActionLink("Šifrarnik", "Index", "TipPredmetas"))
                </th>
                <th>
                    Ishodi učenja
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Predmeti)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Naziv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TipPredmeta)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IshodiUcenja)
                    </td>
                    <td class="btn-group btn-group-sm">
                        @*
                            Html.ActionLink("Pojedinosti", "Details", "Predmets", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-sm btn-primary" })
                        *@
                        @Html.ActionLink("Uredi", "Edit", "Predmets", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-sm btn-success" })
                        @Html.ActionLink("Brisanje", "Delete", "Predmets", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-sm btn-danger" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    @Html.Partial("~/Views/Shared/_NoEntries.cshtml")
}

@section scripts {
    <script>
        $(document).ready(function () {
            $('#PredmetiTable').DataTable({
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.10.12/i18n/Croatian.json'
                }
            });
        });
    </script>
}

ZI/Views/StudijskiPrograms/Edit.cshtml
@model BLL.StudijskiProgram

@{
    ViewBag.Title = "Uređivanje";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Studijski program</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.TipStudijaId, "TipStudijaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipStudijaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipStudijaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FakultetId, "FakultetId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FakultetId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FakultetId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Trajanje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Trajanje, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Trajanje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Pohrani" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Svi studijski programi", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ZI/Views/StudijskiPrograms/Index.cshtml
@model IEnumerable<BLL.StudijskiProgram>

@{
    ViewBag.Title = "Studijski programi";
}

<h2>
    @ViewBag.Title
    @Html.ActionLink("Novi zapis", "Create", null, htmlAttributes: new { @class = "pull-right btn btn-primary" })
</h2>

<p>
</p>
<div class="well row">
    <div class="col-xs-4">
        Prikazano <strong>@Model.Count()</strong> program(a).<br />
    </div>
    <form id="filterForm" class="col-sm-8">
        <div class="col-sm-6">
            <label for="fakultetId">Fakultet</label>
            @Html.DropDownList("fakultetId", null, htmlAttributes: new { @class = "form-control" })
        </div>
        <div class="col-sm-6">
            <label for="tipStudijaId">Tip studija</label>
            @Html.DropDownList("tipStudijaId", null, htmlAttributes: new { @class = "form-control" })
        </div>
    </form>
</div>

@if (Model.Count() > 0)
{
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Naziv)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Trajanje)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Fakultet)
                </th>
                <th>
                    Tip studija
                    (@Html.ActionLink("Šifrarnik", "Index", "TipStudijas"))
                </th>
                <th width="250"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Naziv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Trajanje)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fakultet)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TipStudija)
                    </td>
                    <td class="btn-group btn-group-sm">
                        @Html.ActionLink("Pojedinosti", "Details", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-sm btn-primary" })
                        @Html.ActionLink("Uredi", "Edit", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-sm btn-success" })
                        @Html.ActionLink("Brisanje", "Delete", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-sm btn-danger" })
                    </td>
                </tr>
            }
        </tbody>

    </table>
}
else
{
    @Html.Partial("~/Views/Shared/_NoEntries.cshtml")
}

@section scripts {
    <script>
        var ff = '#filterForm';
        $(ff).on('change', function () {
            this.submit();
        });
    </script>
}