ZI/Models/FakultetViewModel.cs
using BLL;
using System.Collections.Generic;

namespace ZI.Models
{
    public class FakultetViewModel
    {
        public Fakultet Fakultet { get; set; }
        public IEnumerable<OrganizacijskaJedinica> OrgJedList { get; set; }
        public PagingInfo PagingInfo { get; set; }
    }
}

ZI/Controllers/FakultetsController.cs
using BLL;
using BLL.BLLProviders;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ZI.Models;

namespace DZ22.Controllers
{
    /// <summary>
    /// Upravljač za rad s master-detail stranicom Fakulteti.
    /// </summary>
    public class FakultetsController : Controller
    {
        
        private BLL.BLLProviders.FakultetBLL fakBLL = new BLL.BLLProviders.FakultetBLL();

        private BLL.BLLProviders.SveucilisteBLL sveBLL = new BLL.BLLProviders.SveucilisteBLL();
        private List<Fakultet> fakulteti = new List<Fakultet>();


        /// <summary>
        /// GET postupak za prikaz Index stranice za fakultete
        /// Dohvaća popis svih fakulteta, sortira ih po parametrima i predaje pogledu.
        /// </summary>
        /// <param name="sveucilisteId">Uvjet sortiranja fakulteta</param>
        /// <returns>Rezultat akcije upravljača prikazuje popis faulteta.</returns>
        public ActionResult Index(int? sveucilisteId)
        {
            if (!sveucilisteId.HasValue || sveucilisteId == -1) {
                fakulteti = fakBLL.FetchAll().ToList();
            } else {
                fakulteti = fakBLL.FetchBySveuciliste(sveucilisteId.Value).ToList();
                
            }
            var sveucilista = sveBLL.FetchAll();
            sveucilista.Insert(0, new BLL.Sveuciliste() { Id = -1, Naziv = "--- Odaberite sveučilište ---" });

            object svSel = sveucilisteId.HasValue ? sveBLL.FetchByID(sveucilisteId.Value) : null;
            ViewData["SveucilisteId"] = new SelectList(sveucilista, "Id", "Naziv", svSel);
            return View(fakulteti);
        }

        /// <summary>
        /// Dohvaća popis svih organizacijskih jedinica određenog fakulteta
        /// Namještava straničenje
        /// </summary>
        /// <param name="id">Šifra fakulteta čije podatke želimo prikazati</param>
        /// <returns>Rezultat akcije upravljača prikazuje pogled Details s odabranim fakultetom i pripadajućim organizacijskim jedinicama.</returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var fakultet = fakBLL.FetchByID(id.Value);
            if (fakultet == null)
            {
                return HttpNotFound();
            }

            var bllOrgJed = new OrganizacijskaJedinicaBLL();
            var OrgJeds = bllOrgJed.FetchAll().Where(x => x.FakultetId == fakultet.Id);

            FakultetViewModel model = new FakultetViewModel
            {
                Fakultet = fakultet,
                OrgJedList = OrgJeds.ToList(),
                PagingInfo = null
            };

            return View(model);
        }

        /// <summary>
        /// Upravitelj za dohvaćanje podataka potrebnih za stranicu za kreiranje fakulteta.
        /// </summary>
        /// <param name="sveucID">Šifra sveučilišta kojem pripada fakultet koji kreiramo</param>
        /// <returns>Pogled za kreiranje fakulteta</returns>
        public ActionResult Create(int? sveucID)
        {
            var sveucilisteBLL = new BLL.BLLProviders.SveucilisteBLL();
            ViewBag.SveucilisteId = new SelectList(sveucilisteBLL.FetchAll(), "Id", "Naziv", sveucID);
            return View();
        }

        /// <summary>
        /// Upravitelj za dohvaćanje podataka potrebnih za stranicu za kreiranje fakulteta.
        /// </summary>
        /// <param name="fakultet">Novi fakultet koji se dodaje</param>
        /// <returns>Pogled za kreiranje fakulteta</returns>
        [HttpPost][ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SveucilisteId,Naziv,Kratica,Adresa,OIB,URL,IBAN")] BLL.Fakultet fakultet)
        {
            if (ModelState.IsValid)
            {
                fakBLL.Insert(fakultet);
                return RedirectToAction("Index");
            }
            var sveucilisteBLL = new BLL.BLLProviders.SveucilisteBLL();
            object selectedSv = sveBLL.FetchByID(fakultet.SveucilisteId);
            ViewBag.SveucilisteId = new SelectList(sveucilisteBLL.FetchAll(), "Id", "Naziv", selectedSv);
            return View(fakultet);
        }


        /// <summary>
        /// Upravitelj za dohvaćanje i prikaz podataka o fakultetu koji se uređuje.
        /// </summary>
        /// <param name="id">Broj fakulteta koji se uređuje</param>
        /// <returns>Pogled za uređivanje fakulteta</returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var fakultet = fakBLL.FetchByID(id.Value);
            if (fakultet == null)
            {
                return HttpNotFound();
            }
            var sveucilisteBLL = new BLL.BLLProviders.SveucilisteBLL();
            ViewBag.SveucilisteId = new SelectList(sveucilisteBLL.FetchAll(), "Id", "Naziv", fakultet.SveucilisteId);
            return View(fakultet);
        }

        /// <summary>
        /// POST metoda za uređivanje fakulteta
        /// </summary>
        /// <param name="fakultet">Podaci o fakultetu koje je potrebno spremiti</param>
        /// <returns>Stranicu Index na fakultetu koji je bio uređen</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SveucilisteId,Naziv,Kratica,Adresa,OIB,URL,IBAN")] BLL.Fakultet fakultet)
        {
            if (ModelState.IsValid)
            {
                fakBLL.Update(fakultet);
                return RedirectToAction("Index");
            }
            var sveucilisteBLL = new BLL.BLLProviders.SveucilisteBLL();
            ViewBag.SveucilisteId = new SelectList(sveucilisteBLL.FetchAll(), "Id", "Naziv", fakultet.SveucilisteId);
            return View(fakultet);
        }


        /// <summary>
        /// Upravitelj za dohvaćanje podataka za prikaz pogleda za potvrđivanje brisanja.
        /// </summary>
        /// <param name="id">Broj računa koji se briše</param>
        /// <returns>Stranicu za potvrdu brisanja računa</returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var fakultet = fakBLL.FetchByID(id.Value);
            if (fakultet == null)
            {
                return HttpNotFound();
            }
            return View(fakultet);
        }

        /// <summary>
        /// POST metoda koja se poziva kad se potvrdi brisanje fakulteta.
        /// </summary>
        /// <param name="id">Broj fakulteta koji se briše</param>
        /// <returns>Osvježenu Index stranicu s preostalim fakultetima</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var fakultet = fakBLL.FetchByID(id);
            fakBLL.Delete(fakultet);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZI/Controllers/OrganizacijskaJedinicasController.cs
using System.Net;
using System.Web.Mvc;

namespace DZ22.Controllers
{
    /// <summary>
    /// Upravljač za rad s organizacijskim jediniama (Detalji) koje pripadaju odabranom fakultetu (Master).
    /// </summary>
    public class OrganizacijskaJedinicasController : Controller
    {
        private BLL.BLLProviders.OrganizacijskaJedinicaBLL ojBLL = new BLL.BLLProviders.OrganizacijskaJedinicaBLL();


        /// <summary>
        /// GET postupak za prikaz Index stranice za org.jedinice
        /// Dohvaća popis svih org.jedinica
        /// </summary>
        /// <returns>Rezultat akcije upravljača prikazuje popis org.jedinica.</returns>
        public ActionResult Index()
        {
            return View(ojBLL.FetchAll());
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var organizacijskaJedinica = ojBLL.FetchByID(id.Value);
            if (organizacijskaJedinica == null)
            {
                return HttpNotFound();
            }
            return View(organizacijskaJedinica);
        }

        /// <summary>
        /// Upravitelj za dohvaćanje podataka potrebnih za stranicu za kreiranje org.jedinica.
        /// </summary>
        /// <param name="fakID">Šifra fakulteta kojem pripada org.jedinica koju kreiramo</param>
        /// <returns>Pogled za kreiranje org.jedinica</returns>
        public ActionResult Create(int? fakID)
        {

            var fakBLL = new BLL.BLLProviders.FakultetBLL();
            var tojBLL = new BLL.BLLProviders.TipOrgJedBLL();
            ViewBag.FakultetId = new SelectList(fakBLL.FetchAll(), "Id", "Naziv", fakID);
            ViewBag.TipOrgJedId = new SelectList(tojBLL.FetchAll(), "Id", "Naziv");

            return View();
        }

        /// <summary>
        /// Upravitelj za dohvaćanje podataka potrebnih za stranicu za kreiranje org.jedinica.
        /// </summary>
        /// <param name="organizacijskaJedinica">Nova org.jed koja se dodaje</param>
        /// <returns>Pogled za kreiranje org.jedinica</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  ActionResult Create([Bind(Include = "FakultetId,TipOrgJedId,Naziv,Kratica,Email")] BLL.OrganizacijskaJedinica organizacijskaJedinica)
        {
            if (ModelState.IsValid)
            {
                ojBLL.Insert(organizacijskaJedinica);
                return RedirectToAction("Details", "Fakultets", new { id = organizacijskaJedinica.FakultetId });
            }

            var fakBLL = new BLL.BLLProviders.FakultetBLL();
            object selectedFAK = fakBLL.FetchByID(organizacijskaJedinica.FakultetId);
            ViewBag.FakultetId = new SelectList(fakBLL.FetchAll(), "Id", "Naziv", selectedFAK);
            var tojBLL = new BLL.BLLProviders.TipOrgJedBLL();
            ViewBag.TipOrgJedId = new SelectList(tojBLL.FetchAll(), "Id", "Naziv", organizacijskaJedinica.TipOrgJedId);
            return View(organizacijskaJedinica);
        }


        /// <summary>
        /// Upravitelj za dohvaćanje i prikaz podataka o org.jedinici koja se uređuje.
        /// </summary>
        /// <param name="id">Broj org.jedinice koja se uređuje</param>
        /// <returns>Pogled za uređivanje org.jedinice</returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var organizacijskaJedinica = ojBLL.FetchByID(id.Value);
            if (organizacijskaJedinica == null)
            {
                return HttpNotFound();
            }
            var fakBLL = new BLL.BLLProviders.FakultetBLL();
            ViewBag.FakultetId = new SelectList(fakBLL.FetchAll(), "Id", "Naziv", organizacijskaJedinica.FakultetId);
            var tojBLL = new BLL.BLLProviders.TipOrgJedBLL();
            ViewBag.TipOrgJedId = new SelectList(tojBLL.FetchAll(), "Id", "Naziv", organizacijskaJedinica.TipOrgJedId);
            return View(organizacijskaJedinica);
        }

        /// <summary>
        /// POST metoda za uređivanje org.jedinica
        /// </summary>
        /// <param name="organizacijskaJedinica">Podaci o org.jed koje je potrebno spremiti</param>
        /// <returns>Stranicu Index na org.jed. koja je bila uređena</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  ActionResult Edit([Bind(Include = "Id,FakultetId,TipOrgJedId,Naziv,Kratica,Email")] BLL.OrganizacijskaJedinica organizacijskaJedinica)
        {
            if (ModelState.IsValid)
            {
                ojBLL.Update(organizacijskaJedinica);
                return RedirectToAction("Details", "Fakultets", new { id = organizacijskaJedinica.FakultetId });
            }
            var fakBLL = new BLL.BLLProviders.FakultetBLL();
            ViewBag.FakultetId = new SelectList(fakBLL.FetchAll(), "Id", "Naziv", organizacijskaJedinica.FakultetId);
            var tojBLL = new BLL.BLLProviders.TipOrgJedBLL();
            ViewBag.TipOrgJedId = new SelectList(tojBLL.FetchAll(), "Id", "Naziv", organizacijskaJedinica.TipOrgJedId);
            return View(organizacijskaJedinica);
        }

        /// <summary>
        /// Upravitelj za dohvaćanje podataka za prikaz pogleda za potvrđivanje brisanja.
        /// </summary>
        /// <param name="id">Broj org.jed. koja se briše</param>
        /// <returns>Stranicu za potvrdu brisanja org.jed.</returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var organizacijskaJedinica = ojBLL.FetchByID(id.Value);
            if (organizacijskaJedinica == null)
            {
                return HttpNotFound();
            }
            return View(organizacijskaJedinica);
        }

        /// <summary>
        /// POST metoda koja se poziva kad se potvrdi brisanje org.jed.
        /// </summary>
        /// <param name="id">Broj org.jed koja se briše</param>
        /// <returns>Osvježenu Detail stranicu s preostalim org.jed.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public  ActionResult DeleteConfirmed(int id)
        {
            var organizacijskaJedinica = ojBLL.FetchByID(id);
            ojBLL.Delete(organizacijskaJedinica);
            return RedirectToAction("Details","Fakultets", new { id = organizacijskaJedinica.FakultetId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZI/Controllers/TipOrgJedsController.cs
using System.Net;
using System.Web.Mvc;

namespace DZ22.Controllers
{
    public class TipOrgJedsController : Controller
    {
        private BLL.BLLProviders.TipOrgJedBLL tojBLL = new BLL.BLLProviders.TipOrgJedBLL();


        public ActionResult Index()
        {
            return View(tojBLL.FetchAll());
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tipOrgJed = tojBLL.FetchByID(id.Value);
            if (tipOrgJed == null)
            {
                return HttpNotFound();
            }
            return View(tipOrgJed);
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Naziv")] BLL.TipOrgJed tipOrgJed)
        {
            if (ModelState.IsValid)
            {
                tojBLL.Insert(tipOrgJed);
                return RedirectToAction("Index");
            }

            return View(tipOrgJed);
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tipOrgJed = tojBLL.FetchByID(id.Value);
            if (tipOrgJed == null)
            {
                return HttpNotFound();
            }
            return View(tipOrgJed);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Naziv")] BLL.TipOrgJed tipOrgJed)
        {
            if (ModelState.IsValid)
            {
                tojBLL.Update(tipOrgJed);
                return RedirectToAction("Index");
            }
            return View(tipOrgJed);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tipOrgJed = tojBLL.FetchByID(id.Value);
            if (tipOrgJed == null)
            {
                return HttpNotFound();
            }
            return View(tipOrgJed);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var tipOrgJed = tojBLL.FetchByID(id);
            tojBLL.Delete(tipOrgJed);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZI/Views/Fakultets/Create.cshtml
@model BLL.Fakultet

@{
    ViewBag.Title = "Create";
}

<br /><h2>Novi zapis fakulteta</h2><br />


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="well row">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.SveucilisteId, "SveucilisteId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("SveucilisteId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SveucilisteId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Kratica, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Kratica, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Kratica, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Adresa, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Adresa, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Adresa, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OIB, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OIB, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OIB, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IBAN, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IBAN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IBAN, "", new { @class = "text-danger" })
                </div>
            </div>
    </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Dodaj" class="btn btn-primary" />
                    <input type="button" onclick="window.history.back()" value="Povratak" class="btn btn-danger" />
                </div>
            </div>
        </div>
        }

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

ZI/Views/Fakultets/Delete.cshtml
@model BLL.Fakultet

@{
    ViewBag.Title = "Delete";
}

<br /><h2>Izbriši zapis</h2><br />

<h3>Jeste li sigurni da želite izbrisati ovaj zapis?</h3>
<div>
    <div class="well row">
        <h3><b>@Html.DisplayFor(model => model.Naziv)</b></h3>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Naziv)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Naziv)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Kratica)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Kratica)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Adresa)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Adresa)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OIB)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OIB)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.URL)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.URL)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IBAN)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IBAN)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SveucilisteNaziv)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SveucilisteNaziv)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                <div class="col-md-offset-1 col-md-10">
                    <input type="submit" value="Izbriši" class="btn btn-danger" />
                    <input type="submit" onclick="window.history.back()" value="Odustani" class="btn btn-primary" />
                </div>
            </div>
            <br />
        }
    </div>
</div>

ZI/Views/Fakultets/Details.cshtml
@model ZI.Models.FakultetViewModel

@{
    ViewBag.Title = "Details";
}
<br /><h2><b>@Html.DisplayFor(model => model.Fakultet.Naziv)</b></h2><br />

<h3>Opći podatci</h3>
<div class="well row">
    <div class="col-xs-4">
        @Html.ActionLink("Uredi zapis", "Edit", "Fakultets", new { id = Model.Fakultet.Id }, htmlAttributes: new { @class = "btn btn btn-default" })
    </div>
    <br /><br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Fakultet.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fakultet.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fakultet.Kratica)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fakultet.Kratica)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fakultet.Adresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fakultet.Adresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fakultet.OIB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fakultet.OIB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fakultet.URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fakultet.URL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fakultet.IBAN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fakultet.IBAN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fakultet.SveucilisteNaziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fakultet.SveucilisteNaziv)
        </dd>

    </dl>


</div>
<br />
<h3>Organizacijske jedinice fakulteta  |  
    @Html.ActionLink("Dodaj novi zapis", "Create", "OrganizacijskaJedinicas", new { fakID = Model.Fakultet.Id }, htmlAttributes: new { @class = "btn btn-success" })
</h3>

<div class="well row">

    @if (Model.OrgJedList.Count() > 0)
    {
        <br>
        <table class="table table-striped table-hover" id="OrgJedsTable">
            <thead>
                <tr>
                    <th>
                        Naziv jedinice
                    </th>
                    <th>
                        Kratica
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                        Tip
                        @Html.ActionLink("(Šifrarnik)", "Index", "TipOrgJeds")
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.OrgJedList)
                {
                    <tr>
                        <th>
                            @Html.DisplayFor(modelItem => item.Naziv)
                        </th>
                        <th>
                            @Html.DisplayFor(modelItem => item.Kratica)
                        </th>
                        <th>
                            @Html.DisplayFor(modelItem => item.Email)
                        </th>
                        <th>
                            @Html.DisplayFor(modelItem => item.TipOrgJedNaziv)
                        </th>
                        <th>
                            @Html.ActionLink("Uredi", "Edit", "OrganizacijskaJedinicas", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-sm btn-default" })
                            @Html.ActionLink("Izbriši", "Delete", "OrganizacijskaJedinicas", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-sm btn-danger" })
                        </th>
                    </tr>
                }
            </tbody>

        </table>
    }
    else
    {
        @Html.Partial("~/Views/Shared/_NoEntries.cshtml")
    }
</div>


<p>
    @Html.ActionLink("Povratak na listu fakulteta", "Index")
</p>

@section scripts {
<script>
        $(document).ready(function () {
            $('#OrgJedsTable').DataTable({
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.10.12/i18n/Croatian.json'
                }
            });
        });
</script>
}