ZI/Controllers/NastavniPlansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DZ22.Controllers
{
    /// <summary>
    /// Upravljač za rad sa stranicama vezane uz nastavne planove
    /// </summary>
    public class NastavniPlansController : Controller
    {
        BLL.BLLProviders.NastavniPlanBLL bllNP = new BLL.BLLProviders.NastavniPlanBLL();
        BLL.BLLProviders.PredmetBLL bllP = new BLL.BLLProviders.PredmetBLL();

        /// <summary>
        /// GET postupak za dohvaćanje podataka Master-details stranice predmeta i nastavnih planova.
        /// </summary>
        /// <param name="id">Primarni ključ predmeta</param>
        /// <returns>Pogled s master-details prikazom predmeta i pripadnih nastavnih planova</returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var predmet = bllP.FetchById(id.Value);
            if (predmet == null)
            {
                return HttpNotFound();
            }
            var nastavniPlanovi = bllNP.Fetch(id);
            var model = new ZI.Models.PredmetNastavniPlanoviViewModel()
            {
                Predmet = predmet,
                NastavniPlanovi = nastavniPlanovi
            };

            return View(model);
        }

        /// <summary>
        /// GET postupak za otvaranje obrasca za unos novog nastavnog plana
        /// </summary>
        /// <returns>Pogled s obrascem za unos i pohranu novog nastavnog plana</returns>
        public ActionResult Create(int predmetId)
        {
            ViewBag.PredmetId = predmetId;
            return View();
        }

        /// <summary>
        /// POST postupak za pohranu novog nastavnog plana
        /// </summary>
        /// <param name="nastavniPlan">BLL razred koji učahuruje podatke o novounesenom studijskom programu</param>
        /// <returns>Vraća Index pogled s popisom svih studijskih programa u slučaju uspješne pohrane, a inače prikazuje prethodni obrazac za unos s pripadnim greškama</returns>
        // POST: StudijskiPrograms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PredmetId,GodinaOdrzavanja,Semestar,ECTS,SatiPredavanja,SatiLaboratorija,SatiVjezbi")] BLL.NastavniPlan nastavniPlan)
        {
            if (ModelState.IsValid)
            {
                bllNP.Insert(nastavniPlan);
                return RedirectToAction("Details", "Predmets", new { id = nastavniPlan.PredmetId });
            }
            
            return View(nastavniPlan);
        }

        /// <summary>
        /// GET postupak za dohvaćanje podataka obrasca za uređivanje podataka o nastavnom planu
        /// </summary>
        /// <param name="id">Primarni ključ nastavnog plana koji se uređuje</param>
        /// <returns>Pogled s obrascem za uređivanje podataka o nastavnom planu</returns>
        // GET: StudijskiPrograms/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var nastavniPlan = bllNP.FetchById(id.Value);
            if (nastavniPlan == null)
            {
                return HttpNotFound();
            }

            ViewBag.PredmetId = nastavniPlan.PredmetId;
            return View(nastavniPlan);
        }

        /// <summary>
        /// POST postupak za pohranu izmijenjenih podataka o nastavnom planu
        /// </summary>
        /// <param name="nastavniPlan">BLL razred koji učahuruje izmijenjene podatke o nastavnom planu</param>
        /// <returns></returns>
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind(Include = "PredmetId,GodinaOdrzavanja,Semestar,ECTS,SatiPredavanja,SatiLaboratorija,SatiVjezbi")] BLL.NastavniPlan nastavniPlan)
        {
            nastavniPlan.Id = id;
            if (ModelState.IsValid)
            {
                bllNP.Update(nastavniPlan);
                return RedirectToAction("Details", "Predmets", new { id = nastavniPlan.PredmetId });
            }

            ViewBag.PredmetId = nastavniPlan.PredmetId;
            return View(nastavniPlan);
        }

        /// <summary>
        /// GET postupak za dohvaćanje podataka o nastavnom planu koji se želi brisati
        /// </summary>
        /// <param name="id">Primarni ključ nastavnog plana koji se želi brisati</param>
        /// <returns>Master podaci o nastavnom planu koji se želi brisati</returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var nastavniPlan = bllNP.FetchById(id.Value);
            if (nastavniPlan == null)
            {
                return HttpNotFound();
            }
            return View(nastavniPlan);
        }

        /// <summary>
        /// POST postupak provođenje brisanja nastavnog plana
        /// </summary>
        /// <param name="id">Primarni ključ nastavnog plana za koji se potvrđuje brisanje</param>
        /// <returns>Pogled s predmetom i popisom nastavnih planova u slučaju uspjeha, a inača poruka o pogrešci.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var predmetId = bllNP.FetchById(id).PredmetId;
            bllNP.Delete(id);
            return RedirectToAction("Details", "Predmets", new { id = predmetId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZI/Controllers/PredmetsController.cs
using BLL;
using System.Net;
using System.Web.Mvc;

namespace DZ22.Controllers
{
    public class PredmetsController : Controller
    {
        private BLL.BLLProviders.PredmetBLL bllP = new BLL.BLLProviders.PredmetBLL();
        private BLL.BLLProviders.TipPredmetaBLL bllTP = new BLL.BLLProviders.TipPredmetaBLL();
        private BLL.BLLProviders.StudijskiProgramBLL bllSP = new BLL.BLLProviders.StudijskiProgramBLL();
        private BLL.BLLProviders.NastavniPlanBLL bllNP = new BLL.BLLProviders.NastavniPlanBLL();

        // GET: Predmets
        public ActionResult Index()
        {
            var predmet = bllP.FetchAll();
            return View(predmet);
        }

        // GET: Predmets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var predmet = bllP.FetchById(id.Value);
            if (predmet == null)
            {
                return HttpNotFound();
            }
            var model = new ZI.Models.PredmetNastavniPlanoviViewModel()
            {
                Predmet = predmet,
                NastavniPlanovi = bllNP.Fetch(predmet.Id)
            };
            return View(model);
        }

        // GET: Predmets/Create
        public ActionResult Create(int? studijskiProgramId)
        {
            object selectedSP = studijskiProgramId.HasValue ? bllSP.FetchById(studijskiProgramId.Value) : null;
            ViewBag.StudijskiProgramId = new SelectList(bllSP.FetchAll(), "Id", "Naziv", selectedSP);
            ViewBag.TipPredmetaId = new SelectList(bllTP.FetchAll(), "Id", "Naziv");
            return View();
        }

        // POST: Predmets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int? studijskiProgramId,
            [Bind(Include = "Id,TipPredmetaId,StudijskiProgramId,Naziv,IshodiUcenja")] Predmet predmet)
        {
            if (ModelState.IsValid)
            {
                bllP.Insert(predmet);
                return RedirectToAction("Index");
            }
            
            ViewBag.StudijskiProgramId = new SelectList(bllSP.FetchAll(), "Id", "Naziv", predmet.StudijskiProgramId);
            ViewBag.TipPredmetaId = new SelectList(bllTP.FetchAll(), "Id", "Naziv");
            return View(predmet);
        }

        // GET: Predmets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Predmet predmet = bllP.FetchById(id.Value);
            if (predmet == null)
            {
                return HttpNotFound();
            }
            
            ViewBag.StudijskiProgramId = new SelectList(bllSP.FetchAll(), "Id", "Naziv", predmet.StudijskiProgramId);
            ViewBag.TipPredmetaId = new SelectList(bllTP.FetchAll(), "Id", "Naziv", predmet.TipPredmetaId);
            return View(predmet);
        }

        // POST: Predmets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TipPredmetaId,StudijskiProgramId,Naziv,IshodiUcenja")] Predmet predmet)
        {
            if (ModelState.IsValid)
            {
                bllP.Update(predmet);
                return RedirectToAction("Details", new { id = predmet.Id });
            }
            
            ViewBag.StudijskiProgramId = new SelectList(bllSP.FetchAll(), "Id", "Naziv", predmet.StudijskiProgramId);
            ViewBag.TipPredmetaId = new SelectList(bllTP.FetchAll(), "Id", "Naziv", predmet.TipPredmetaId);
            return View(predmet);
        }

        // GET: Predmets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Predmet predmet = bllP.FetchById(id.Value);
            if (predmet == null)
            {
                return HttpNotFound();
            }
            return View(predmet);
        }

        // POST: Predmets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            bllP.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZI/Controllers/TipPredmetasController.cs
using BLL;
using System.Data.Entity;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DZ22.Controllers
{
    public class TipPredmetasController : Controller
    {
        private BLL.BLLProviders.TipPredmetaBLL bllTP = new BLL.BLLProviders.TipPredmetaBLL();

        // GET: TipPredmetas
        public async Task<ActionResult> Index()
        {
            return View(bllTP.FetchAll());
        }

        // GET: TipPredmetas/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipPredmeta tipPredmeta = bllTP.Fetch(id.Value);
            if (tipPredmeta == null)
            {
                return HttpNotFound();
            }
            return View(tipPredmeta);
        }

        // GET: TipPredmetas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipPredmetas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Naziv")] TipPredmeta tipPredmeta)
        {
            if (ModelState.IsValid)
            {
                bllTP.Insert(tipPredmeta);
                return RedirectToAction("Index");
            }

            return View(tipPredmeta);
        }

        // GET: TipPredmetas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipPredmeta tipPredmeta = bllTP.Fetch(id.Value);
            if (tipPredmeta == null)
            {
                return HttpNotFound();
            }
            return View(tipPredmeta);
        }

        // POST: TipPredmetas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Naziv")] TipPredmeta tipPredmeta)
        {
            if (ModelState.IsValid)
            {
                bllTP.Update(tipPredmeta);
                return RedirectToAction("Index");
            }
            return View(tipPredmeta);
        }

        // GET: TipPredmetas/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipPredmeta tipPredmeta = bllTP.Fetch(id.Value);
            if (tipPredmeta == null)
            {
                return HttpNotFound();
            }
            return View(tipPredmeta);
        }

        // POST: TipPredmetas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            bllTP.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZI/Views/Predmets/Create.cshtml
@model BLL.Predmet

@{
    ViewBag.Title = "Stvaranje";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Predmet</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TipPredmetaId, "TipPredmetaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipPredmetaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipPredmetaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudijskiProgramId, "StudijskiProgramId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudijskiProgramId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudijskiProgramId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IshodiUcenja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.IshodiUcenja, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IshodiUcenja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Stvori" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ZI/Views/Predmets/Delete.cshtml
@model BLL.Predmet

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Predmet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IshodiUcenja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IshodiUcenja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipPredmeta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipPredmeta)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Odustani", "Details", "StudijskiPrograms", new { id = Model.StudijskiProgramId }, new { })
        </div>
    }
</div>

ZI/Views/Predmets/Details.cshtml
@model ZI.Models.PredmetNastavniPlanoviViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Predmet i nastavni planovi</h2>

<div class="well">
    @Html.ActionLink("Uredi predmet", "Edit", new { id = Model.Predmet.Id }, htmlAttributes: new { @class = "pull-right btn btn-success" })
    <h4>Predmet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Predmet.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Predmet.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Predmet.TipPredmeta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Predmet.TipPredmeta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Predmet.StudijskiProgram)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Predmet.StudijskiProgram)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Predmet.IshodiUcenja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Predmet.IshodiUcenja)
        </dd>
    </dl>
</div>

<h4>
    @Html.ActionLink("Novi nastavni plan", "Create", "NastavniPlans", new { predmetId = Model.Predmet.Id }, htmlAttributes: new { @class = "pull-right btn btn-primary" })
    Nastavni planovi
</h4>
<hr />

@if (Model.NastavniPlanovi.Count() > 0)
{
    <table class="table table-hover table-striped" id="NastavniPlanoviTable">
        <thead>
            <tr>
                <th>
                    ECTS bodovi
                </th>
                <th>
                    Semestar
                </th>
                <th>
                    Godina održavanja
                </th>
                <th>Sati predavanja</th>
                <th>Sati laboratorija</th>
                <th>Sati vježbi</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.NastavniPlanovi)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ECTS)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Semestar)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GodinaOdrzavanja)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SatiPredavanja)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SatiLaboratorija)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SatiVjezbi)
                    </td>
                    <td class="btn-group btn-group-sm">
                        @Html.ActionLink("Uredi", "Edit", "NastavniPlans", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-sm btn-success" })
                        @Html.ActionLink("Brisanje", "Delete", "NastavniPlans", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-sm btn-danger" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    @Html.Partial("~/Views/Shared/_NoEntries.cshtml")
}

@section scripts {
    <script>
        $(document).ready(function () {
            $('#NastavniPlanoviTable').DataTable({
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.10.12/i18n/Croatian.json'
                }
            });
        });
    </script>
}

ZI/Views/Predmets/Edit.cshtml
@model BLL.Predmet

@{
    ViewBag.Title = "Uredi";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Predmet</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.TipPredmetaId, "TipPredmetaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipPredmetaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipPredmetaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudijskiProgramId, "StudijskiProgramId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudijskiProgramId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudijskiProgramId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IshodiUcenja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.IshodiUcenja, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IshodiUcenja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Pohrani" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Popis svih predmeta", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ZI/Views/Predmets/Index.cshtml
@model IEnumerable<BLL.Predmet>

@{
    ViewBag.Title = "Predmeti";
}

<h2>@ViewBag.Title
    @Html.ActionLink("Novi predmet", "Create", null, new { @class = "btn btn-primary" })
</h2>
<hr />

<table id="PredmetiTable" class="table table-hover table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Naziv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipPredmeta)
                (@Html.ActionLink("Šifrarnik", "Index", "TipPredmetas"))
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StudijskiProgram)
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Naziv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipPredmeta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StudijskiProgram)
                </td>
                <td class="btn-group btn-group-sm" width="225">
                    @Html.ActionLink("Pojedinosti", "Details", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-sm btn-primary" })
                    @Html.ActionLink("Uredi", "Edit", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-sm btn-success" })
                    @Html.ActionLink("Brisanje", "Delete", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-sm btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>


@section scripts {
    <script>
        $(document).ready(function () {
            $('#PredmetiTable').DataTable({
                language: {
                    url: '//cdn.datatables.net/plug-ins/1.10.12/i18n/Croatian.json'
                }
            });
        });
    </script>
}